# Generated by Django 3.0 on 2019-12-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
